#!/bin/bash

# Parse input
DIR="$1"


# Check if DIR is valid
if [ -z "$DIR" ]; then
  echo "Please specify a directory"
  exit 1
fi

if [ ! -d "$DIR" ]; then
  echo "Creating directory: $DIR"
  mkdir -p "$DIR"
fi

if [ ! -f "$DIR/disk.qcow2" ]; then
  echo "Creating disk: $DIR/disk.qcow2"
  qemu-img create -f qcow2 "$DIR/disk.qcow2" 10G
fi

if [ ! -f "$DIR/ovmf_vars.fd" ]; then
  echo "Creating UEFI store: $DIR/ovmf_vars.fd"
  dd if=/dev/zero conv=sync bs=1m count=64 of="$DIR/ovmf_vars.fd"
fi

echo "Done"
